server:
  port: 8002
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://39.108.146.136:3306/leyou
    username: root
    password: 062200
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
eureka:
  client:
    service-url:
      defaultZone: http://39.108.146.136:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 39.108.146.136
    instance-id: ${spring.application.name}:${server.port}